[package]
name = "gsr-ui"
type = "executable"
version = "0.1.0"
platforms = ["posix"]

[lang.cpp]
version = "c++17"

[config]
ignore_dirs = ["build", "gsr-window-name"]

[dependencies]
xcomposite = ">=0"