[package]
name = "gsr-ui"
type = "executable"
version = "1.2.1"
platforms = ["posix"]

[lang.cpp]
version = "c++17"

[config]
ignore_dirs = ["build", "tools"]

[dependencies]
xcomposite = ">=0"
xfixes = ">=0"
xi = ">=0"
xcursor = ">=1"
libpulse-simple = ">=0"
