[package]
name = "gsr-overlay"
type = "executable"
version = "0.1.0"
platforms = ["posix"]

[lang.cpp]
version = "c++17"

[config]
ignore_dirs = ["build", "gpu-screen-recorder-overlay-daemon"]

[dependencies]
xcomposite = ">=0"